apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-migrations
data:
  {{- $root := . }}
  {{ range $path, $_ := .Files.Glob "db-migrations/*.sql" }}
  {{ base $path }}: "{{ $root.Files.Get $path }}"
  {{- end }}
